### ISSUE TITLE
non-repeating script

### ISSUE THREAD

**Issue by luminous122** [Hchong16/lost-ark-auto-fisher#1]
the bot does not repeat the command when it fails to pull the rod. when it fails to pull the rod the bot will stop and have to repeat the command manually

**Comment by Hchong16** [comment]
I'll take a look soon! I received similar reports from other users on this issue.

**Comment by Hchong16** [comment]
While I wasn't able to reproduce the issue (the good old works on my machine, but not on others...), I made some adjustments on the delays for success/failed catches.

Let me know if the issue still persist and I have one other solution in mind!

**Comment by Hchong16** [comment]
Marking as done. Reopen if the issue persists 👀.
